services:
  metamesh-application:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8081:8080"
    environment:
      - PORT=8080
      - MONGO_URI=mongodb://metameshdatabase:CCyxYmEsyHcxhb2qkpOvlAxwDAuP0jBAaIQkHeyL3RHJ5XzlOdBoRaIxel8V2aaCtCfiIW9XErKAACDbVoJoxQ==@metameshdatabase.mongo.cosmos.azure.com:10255/?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@metameshdatabase@
      - DATABASE_NAME=metameshdatabase
      - API_VERSION=1.0.0
      - ALLOWED_ORIGINS=*
    depends_on:
      - mongodb
    restart: always

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
