name: Deploy to Azure Spring Apps

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build project
        run: mvn clean package

      - name: Deploy to Azure Spring Apps
        run: |
          az spring app deploy \
            --name metamesh-api \
            --service metamesh-app \
            --resource-group my-resource-group \
            --artifact-path "target\metamesh-0.0.1-SNAPSHOT.jar"